sonar.projectKey=mini-task-management
sonar.projectName=Mini Task Management
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=MiniTaskManagement.Api,task-ui
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/.next/**,**/coverage/**,**/Migrations/**,**/*.Designer.cs,**/*.g.cs
sonar.tests=MiniTaskManagement.Api
sonar.test.inclusions=**/*Tests.cs,**/*Test.cs
sonar.cpd.exclusions=**/Migrations/**,**/Generated/**

sonar.cs.file.suffixes=**/*.cs
sonar.javascript.file.suffixes=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
