POST http://localhost:5070/api/auth/register
Content-Type: application/json

{
  "fullName": "Admin User",
  "email": "admin@test.com",
  "password": "12345678"
}
###
POST http://localhost:5070/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "12345678"
}
###
POST http://localhost:5070/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8
Content-Type: application/json

{
  "title": "Hoc .NET",
  "description": "Lam bai intern",
  "priority": "High",
  "dueDate": "2026-06-30T00:00:00"
}
###

PUT http://localhost:5070/api/tasks/ab90547a-ef57-4a35-a4d2-4dca45666c92
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8
Content-Type: application/json

{
  "title": "Hoc ASP.NET Core",
  "description": "Hoan thanh CRUD",
  "status": "Done",
  "priority": "Medium",
  "dueDate": "2026-07-01T00:00:00"
}

### Delete Task
DELETE http://localhost:5070/api/tasks/f95b4d18-6d16-4e5b-8ed7-ceaa12e4a88e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8

###
GET http://localhost:5070/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8
###
GET http://localhost:5070/api/tasks?search=net
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8  
###
GET http://localhost:5070/api/tasks?search=hoc&status=Todi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8  

###
### Validation - Empty Title
PUT http://localhost:5070/api/tasks/{caa71780-7c54-4047-8f18-474bbe76ce0b}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8
Content-Type: application/json

{
  "title": "",
  "description": "Update test",
  "status": "Todo",
  "priority": "High",
  "dueDate": "2026-12-31T00:00:00"
}


###
GET http://localhost:5070/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4MjM1OTQ5NiwiaXNzIjoiTWluaVRhc2tNYW5hZ2VtZW50IiwiYXVkIjoiTWluaVRhc2tNYW5hZ2VtZW50In0.w1LSeHwWPiVPq3UI-dLVxYyvaaQR_uYA2IaEBbPOPZ8

###
POST http://localhost:5070/api/auth/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "12345678"
}

###
PUT http://localhost:5070/api/admin/users/3376a365-ee0d-4897-b932-689b579e7439/enable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMzNzZhMzY1LWVlMGQtNDg5Ny1iOTMyLTY4OWI1NzllNzQzOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImFkbWluQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3ODIzNzMyNTAsImlzcyI6Ik1pbmlUYXNrTWFuYWdlbWVudCIsImF1ZCI6Ik1pbmlUYXNrTWFuYWdlbWVudCJ9.Xshf7xBSY1FciwbVUsi9O3T-VvCYfY0zaS7j5SBmFEw

###
POST http://localhost:xxxx/api/auth/login